# Generated by Django 5.2.7 on 2025-11-05 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='SupermachExepense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(db_column='store_name', db_index=True, max_length=100)),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('adress', models.CharField(db_column='address', db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Supermach Expense',
                'verbose_name_plural': 'Supermach Expenses',
                'db_table': 'supermach_expenses',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_column='description', db_index=True, max_length=255)),
                ('quantity', models.IntegerField(db_column='quantity', db_index=True)),
                ('amount', models.DecimalField(db_column='amount', db_index=True, decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('user_id', models.ForeignKey(db_column='user _id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='expenses_module.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='SupermachExpenseItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_column='description', db_index=True, max_length=255)),
                ('quantity', models.IntegerField(db_column='quantity', db_index=True)),
                ('amount', models.DecimalField(db_column='amount', db_index=True, decimal_places=2, max_digits=10)),
                ('supermach_expense_id', models.ForeignKey(db_column='supermach_expense_id', on_delete=django.db.models.deletion.DO_NOTHING, to='expenses_module.supermachexepense')),
            ],
            options={
                'verbose_name': 'Supermach Expense Item',
                'verbose_name_plural': 'Supermach Expense Items',
                'db_table': 'supermach_expense_items',
            },
        ),
    ]
