# Generated by Django 5.2.7 on 2026-05-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_module', '0006_rename_keycloak_user_id_add_need_pay_vitoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='tenant_id',
            field=models.CharField(db_column='tenant_id', db_index=True, help_text='Identificador único do tenant/usuário vindo do Keycloak (sub claim)', max_length=36),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tenant_id',
            field=models.CharField(db_column='tenant_id', db_index=True, help_text='Identificador único do tenant/usuário vindo do Keycloak (sub claim)', max_length=36),
        ),
    ]
