# Generated by Django 5.2.15 on 2026-08-16 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('catalog', '0002_populate_default_categories'),
        ('expenses', '0002_expense_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(db_column='tenant_id', db_index=True, max_length=36)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('day_of_month', models.PositiveSmallIntegerField(db_column='day_of_month', default=1, help_text='Dia do mês em que o gasto se repete (1–28).')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], db_column='payment_method', default='dinheiro', max_length=10)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_templates', to='catalog.expensecategory')),
                ('credit_card', models.ForeignKey(blank=True, db_column='credit_card_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_templates', to='cards.creditcard')),
            ],
            options={
                'verbose_name': 'Recurring Expense Template',
                'verbose_name_plural': 'Recurring Expense Templates',
                'db_table': 'recurring_expense_templates',
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='recexp_tenant_active_idx')],
            },
        ),
    ]
