# Generated by Django 5.2.15 on 2026-08-10 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDebt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('owner_tenant_id', models.CharField(db_column='owner_tenant_id', db_index=True, help_text='tenant_id (sub do Keycloak) do criador do grupo.', max_length=36)),
            ],
            options={
                'verbose_name': 'Shared Debt',
                'verbose_name_plural': 'Shared Debts',
                'db_table': 'shared_debts',
            },
        ),
        migrations.CreateModel(
            name='SharedDebtInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_column='token', db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, db_column='expires_at', null=True)),
                ('created_by_tenant_id', models.CharField(db_column='created_by_tenant_id', max_length=36)),
                ('shared_debt', models.ForeignKey(db_column='shared_debt_id', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='debts.shareddebt')),
            ],
            options={
                'verbose_name': 'Shared Debt Invite',
                'verbose_name_plural': 'Shared Debt Invites',
                'db_table': 'shared_debt_invites',
            },
        ),
        migrations.CreateModel(
            name='SharedDebtMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_column='tenant_id', db_index=True, help_text='tenant_id do Keycloak; NULL até a pessoa entrar via link.', max_length=36, null=True)),
                ('display_name', models.CharField(db_column='display_name', max_length=120)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('shared_debt', models.ForeignKey(db_column='shared_debt_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='debts.shareddebt')),
            ],
            options={
                'verbose_name': 'Shared Debt Member',
                'verbose_name_plural': 'Shared Debt Members',
                'db_table': 'shared_debt_members',
            },
        ),
        migrations.CreateModel(
            name='SharedEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, help_text='Valor positivo da despesa compartilhada.', max_digits=10)),
                ('date', models.DateField(db_column='date')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartao')], db_column='payment_method', db_index=True, default='dinheiro', max_length=10)),
                ('created_by_tenant_id', models.CharField(db_column='created_by_tenant_id', db_index=True, max_length=36)),
                ('credit_card', models.ForeignKey(blank=True, db_column='credit_card_id', help_text='Preenchido apenas quando o usuário atual pagou no próprio cartão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_entries', to='cards.creditcard')),
                ('paid_by', models.ForeignKey(db_column='paid_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='paid_entries', to='debts.shareddebtmember')),
                ('shared_debt', models.ForeignKey(db_column='shared_debt_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='debts.shareddebt')),
            ],
            options={
                'verbose_name': 'Shared Entry',
                'verbose_name_plural': 'Shared Entries',
                'db_table': 'shared_entries',
            },
        ),
        migrations.CreateModel(
            name='SharedEntryParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='debts.sharedentry')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='debts.shareddebtmember')),
            ],
            options={
                'verbose_name': 'Shared Entry Participant',
                'verbose_name_plural': 'Shared Entry Participants',
                'db_table': 'shared_entry_participants',
            },
        ),
        migrations.DeleteModel(
            name='VitoriaDebt',
        ),
        migrations.AddConstraint(
            model_name='shareddebtmember',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', False)), fields=('shared_debt', 'tenant_id'), name='uniq_member_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sharedentryparticipant',
            constraint=models.UniqueConstraint(fields=('entry', 'member'), name='uniq_participant_per_entry'),
        ),
    ]
