# Generated by Django 5.2.15 on 2026-08-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_sharedrecurringtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedentry',
            name='installment_group_id',
            field=models.UUIDField(blank=True, db_column='installment_group_id', db_index=True, help_text='UUID que agrupa todas as parcelas de um mesmo parcelamento.', null=True),
        ),
        migrations.AddField(
            model_name='sharedentry',
            name='installment_number',
            field=models.PositiveSmallIntegerField(db_column='installment_number', default=1, help_text='Número desta parcela (1-based).'),
        ),
        migrations.AddField(
            model_name='sharedentry',
            name='total_installments',
            field=models.PositiveSmallIntegerField(db_column='total_installments', default=1, help_text='Total de parcelas (1 = não parcelado).'),
        ),
        migrations.AlterField(
            model_name='sharedrecurringtemplate',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, help_text='Valor positivo da despesa mensal.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sharedrecurringtemplate',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(db_column='day_of_month', default=1, help_text='Dia do mês em que a despesa se repete (1–28).'),
        ),
        migrations.AlterField(
            model_name='sharedrecurringtemplate',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, help_text='Falso = template pausado, não gera novas entradas.'),
        ),
        migrations.AlterField(
            model_name='sharedrecurringtemplate',
            name='participant_ids',
            field=models.JSONField(db_column='participant_ids', default=list, help_text='Lista de IDs de SharedDebtMember que dividem o gasto.'),
        ),
    ]
