# Generated by Django 5.2.15 on 2026-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(blank=True, db_column='target_amount', decimal_places=2, help_text='Meta opcional (NULL = sem meta definida).', max_digits=12, null=True),
        ),
    ]
